language: node_js
node_js: '8'
branches:
  only:
  - master
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  verbose: true
  on:
    branch: master